/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPublishersRouteImport } from './routes/_authenticated/publishers'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedInsuranceReportRouteImport } from './routes/_authenticated/insurance-report'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedBuyersRouteImport } from './routes/_authenticated/buyers'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedInsuranceRouteRouteImport } from './routes/_authenticated/insurance/route'
import { Route as AuthenticatedInsuranceIndexRouteImport } from './routes/_authenticated/insurance/index'
import { Route as AuthenticatedPublishersPublisherIdRouteImport } from './routes/_authenticated/publishers.$publisherId'
import { Route as AuthenticatedInsuranceTiersRouteImport } from './routes/_authenticated/insurance/tiers'
import { Route as AuthenticatedInsuranceSalesRouteImport } from './routes/_authenticated/insurance/sales'
import { Route as AuthenticatedInsuranceQaRouteImport } from './routes/_authenticated/insurance/qa'
import { Route as AuthenticatedInsurancePayrollRouteImport } from './routes/_authenticated/insurance/payroll'
import { Route as AuthenticatedInsurancePayablesRouteImport } from './routes/_authenticated/insurance/payables'
import { Route as AuthenticatedInsuranceDailyOpsRouteImport } from './routes/_authenticated/insurance/daily-ops'
import { Route as AuthenticatedInsuranceAgentsRouteImport } from './routes/_authenticated/insurance/agents'
import { Route as AuthenticatedBusinessBusinessIdRouteImport } from './routes/_authenticated/business.$businessId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublishersRoute = AuthenticatedPublishersRouteImport.update({
  id: '/publishers',
  path: '/publishers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsuranceReportRoute =
  AuthenticatedInsuranceReportRouteImport.update({
    id: '/insurance-report',
    path: '/insurance-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuyersRoute = AuthenticatedBuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsuranceRouteRoute =
  AuthenticatedInsuranceRouteRouteImport.update({
    id: '/insurance',
    path: '/insurance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInsuranceIndexRoute =
  AuthenticatedInsuranceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInsuranceRouteRoute,
  } as any)
const AuthenticatedPublishersPublisherIdRoute =
  AuthenticatedPublishersPublisherIdRouteImport.update({
    id: '/$publisherId',
    path: '/$publisherId',
    getParentRoute: () => AuthenticatedPublishersRoute,
  } as any)
const AuthenticatedInsuranceTiersRoute =
  AuthenticatedInsuranceTiersRouteImport.update({
    id: '/tiers',
    path: '/tiers',
    getParentRoute: () => AuthenticatedInsuranceRouteRoute,
  } as any)
const AuthenticatedInsuranceSalesRoute =
  AuthenticatedInsuranceSalesRouteImport.update({
    id: '/sales',
    path: '/sales',
    getParentRoute: () => AuthenticatedInsuranceRouteRoute,
  } as any)
const AuthenticatedInsuranceQaRoute =
  AuthenticatedInsuranceQaRouteImport.update({
    id: '/qa',
    path: '/qa',
    getParentRoute: () => AuthenticatedInsuranceRouteRoute,
  } as any)
const AuthenticatedInsurancePayrollRoute =
  AuthenticatedInsurancePayrollRouteImport.update({
    id: '/payroll',
    path: '/payroll',
    getParentRoute: () => AuthenticatedInsuranceRouteRoute,
  } as any)
const AuthenticatedInsurancePayablesRoute =
  AuthenticatedInsurancePayablesRouteImport.update({
    id: '/payables',
    path: '/payables',
    getParentRoute: () => AuthenticatedInsuranceRouteRoute,
  } as any)
const AuthenticatedInsuranceDailyOpsRoute =
  AuthenticatedInsuranceDailyOpsRouteImport.update({
    id: '/daily-ops',
    path: '/daily-ops',
    getParentRoute: () => AuthenticatedInsuranceRouteRoute,
  } as any)
const AuthenticatedInsuranceAgentsRoute =
  AuthenticatedInsuranceAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => AuthenticatedInsuranceRouteRoute,
  } as any)
const AuthenticatedBusinessBusinessIdRoute =
  AuthenticatedBusinessBusinessIdRouteImport.update({
    id: '/business/$businessId',
    path: '/business/$businessId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/insurance': typeof AuthenticatedInsuranceRouteRouteWithChildren
  '/ai': typeof AuthenticatedAiRoute
  '/buyers': typeof AuthenticatedBuyersRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insurance-report': typeof AuthenticatedInsuranceReportRoute
  '/members': typeof AuthenticatedMembersRoute
  '/publishers': typeof AuthenticatedPublishersRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/business/$businessId': typeof AuthenticatedBusinessBusinessIdRoute
  '/insurance/agents': typeof AuthenticatedInsuranceAgentsRoute
  '/insurance/daily-ops': typeof AuthenticatedInsuranceDailyOpsRoute
  '/insurance/payables': typeof AuthenticatedInsurancePayablesRoute
  '/insurance/payroll': typeof AuthenticatedInsurancePayrollRoute
  '/insurance/qa': typeof AuthenticatedInsuranceQaRoute
  '/insurance/sales': typeof AuthenticatedInsuranceSalesRoute
  '/insurance/tiers': typeof AuthenticatedInsuranceTiersRoute
  '/publishers/$publisherId': typeof AuthenticatedPublishersPublisherIdRoute
  '/insurance/': typeof AuthenticatedInsuranceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai': typeof AuthenticatedAiRoute
  '/buyers': typeof AuthenticatedBuyersRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insurance-report': typeof AuthenticatedInsuranceReportRoute
  '/members': typeof AuthenticatedMembersRoute
  '/publishers': typeof AuthenticatedPublishersRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/business/$businessId': typeof AuthenticatedBusinessBusinessIdRoute
  '/insurance/agents': typeof AuthenticatedInsuranceAgentsRoute
  '/insurance/daily-ops': typeof AuthenticatedInsuranceDailyOpsRoute
  '/insurance/payables': typeof AuthenticatedInsurancePayablesRoute
  '/insurance/payroll': typeof AuthenticatedInsurancePayrollRoute
  '/insurance/qa': typeof AuthenticatedInsuranceQaRoute
  '/insurance/sales': typeof AuthenticatedInsuranceSalesRoute
  '/insurance/tiers': typeof AuthenticatedInsuranceTiersRoute
  '/publishers/$publisherId': typeof AuthenticatedPublishersPublisherIdRoute
  '/insurance': typeof AuthenticatedInsuranceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/insurance': typeof AuthenticatedInsuranceRouteRouteWithChildren
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/buyers': typeof AuthenticatedBuyersRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/insurance-report': typeof AuthenticatedInsuranceReportRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/publishers': typeof AuthenticatedPublishersRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/business/$businessId': typeof AuthenticatedBusinessBusinessIdRoute
  '/_authenticated/insurance/agents': typeof AuthenticatedInsuranceAgentsRoute
  '/_authenticated/insurance/daily-ops': typeof AuthenticatedInsuranceDailyOpsRoute
  '/_authenticated/insurance/payables': typeof AuthenticatedInsurancePayablesRoute
  '/_authenticated/insurance/payroll': typeof AuthenticatedInsurancePayrollRoute
  '/_authenticated/insurance/qa': typeof AuthenticatedInsuranceQaRoute
  '/_authenticated/insurance/sales': typeof AuthenticatedInsuranceSalesRoute
  '/_authenticated/insurance/tiers': typeof AuthenticatedInsuranceTiersRoute
  '/_authenticated/publishers/$publisherId': typeof AuthenticatedPublishersPublisherIdRoute
  '/_authenticated/insurance/': typeof AuthenticatedInsuranceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/insurance'
    | '/ai'
    | '/buyers'
    | '/categories'
    | '/dashboard'
    | '/insurance-report'
    | '/members'
    | '/publishers'
    | '/settings'
    | '/transactions'
    | '/business/$businessId'
    | '/insurance/agents'
    | '/insurance/daily-ops'
    | '/insurance/payables'
    | '/insurance/payroll'
    | '/insurance/qa'
    | '/insurance/sales'
    | '/insurance/tiers'
    | '/publishers/$publisherId'
    | '/insurance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ai'
    | '/buyers'
    | '/categories'
    | '/dashboard'
    | '/insurance-report'
    | '/members'
    | '/publishers'
    | '/settings'
    | '/transactions'
    | '/business/$businessId'
    | '/insurance/agents'
    | '/insurance/daily-ops'
    | '/insurance/payables'
    | '/insurance/payroll'
    | '/insurance/qa'
    | '/insurance/sales'
    | '/insurance/tiers'
    | '/publishers/$publisherId'
    | '/insurance'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/insurance'
    | '/_authenticated/ai'
    | '/_authenticated/buyers'
    | '/_authenticated/categories'
    | '/_authenticated/dashboard'
    | '/_authenticated/insurance-report'
    | '/_authenticated/members'
    | '/_authenticated/publishers'
    | '/_authenticated/settings'
    | '/_authenticated/transactions'
    | '/_authenticated/business/$businessId'
    | '/_authenticated/insurance/agents'
    | '/_authenticated/insurance/daily-ops'
    | '/_authenticated/insurance/payables'
    | '/_authenticated/insurance/payroll'
    | '/_authenticated/insurance/qa'
    | '/_authenticated/insurance/sales'
    | '/_authenticated/insurance/tiers'
    | '/_authenticated/publishers/$publisherId'
    | '/_authenticated/insurance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/publishers': {
      id: '/_authenticated/publishers'
      path: '/publishers'
      fullPath: '/publishers'
      preLoaderRoute: typeof AuthenticatedPublishersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insurance-report': {
      id: '/_authenticated/insurance-report'
      path: '/insurance-report'
      fullPath: '/insurance-report'
      preLoaderRoute: typeof AuthenticatedInsuranceReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buyers': {
      id: '/_authenticated/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof AuthenticatedBuyersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insurance': {
      id: '/_authenticated/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof AuthenticatedInsuranceRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insurance/': {
      id: '/_authenticated/insurance/'
      path: '/'
      fullPath: '/insurance/'
      preLoaderRoute: typeof AuthenticatedInsuranceIndexRouteImport
      parentRoute: typeof AuthenticatedInsuranceRouteRoute
    }
    '/_authenticated/publishers/$publisherId': {
      id: '/_authenticated/publishers/$publisherId'
      path: '/$publisherId'
      fullPath: '/publishers/$publisherId'
      preLoaderRoute: typeof AuthenticatedPublishersPublisherIdRouteImport
      parentRoute: typeof AuthenticatedPublishersRoute
    }
    '/_authenticated/insurance/tiers': {
      id: '/_authenticated/insurance/tiers'
      path: '/tiers'
      fullPath: '/insurance/tiers'
      preLoaderRoute: typeof AuthenticatedInsuranceTiersRouteImport
      parentRoute: typeof AuthenticatedInsuranceRouteRoute
    }
    '/_authenticated/insurance/sales': {
      id: '/_authenticated/insurance/sales'
      path: '/sales'
      fullPath: '/insurance/sales'
      preLoaderRoute: typeof AuthenticatedInsuranceSalesRouteImport
      parentRoute: typeof AuthenticatedInsuranceRouteRoute
    }
    '/_authenticated/insurance/qa': {
      id: '/_authenticated/insurance/qa'
      path: '/qa'
      fullPath: '/insurance/qa'
      preLoaderRoute: typeof AuthenticatedInsuranceQaRouteImport
      parentRoute: typeof AuthenticatedInsuranceRouteRoute
    }
    '/_authenticated/insurance/payroll': {
      id: '/_authenticated/insurance/payroll'
      path: '/payroll'
      fullPath: '/insurance/payroll'
      preLoaderRoute: typeof AuthenticatedInsurancePayrollRouteImport
      parentRoute: typeof AuthenticatedInsuranceRouteRoute
    }
    '/_authenticated/insurance/payables': {
      id: '/_authenticated/insurance/payables'
      path: '/payables'
      fullPath: '/insurance/payables'
      preLoaderRoute: typeof AuthenticatedInsurancePayablesRouteImport
      parentRoute: typeof AuthenticatedInsuranceRouteRoute
    }
    '/_authenticated/insurance/daily-ops': {
      id: '/_authenticated/insurance/daily-ops'
      path: '/daily-ops'
      fullPath: '/insurance/daily-ops'
      preLoaderRoute: typeof AuthenticatedInsuranceDailyOpsRouteImport
      parentRoute: typeof AuthenticatedInsuranceRouteRoute
    }
    '/_authenticated/insurance/agents': {
      id: '/_authenticated/insurance/agents'
      path: '/agents'
      fullPath: '/insurance/agents'
      preLoaderRoute: typeof AuthenticatedInsuranceAgentsRouteImport
      parentRoute: typeof AuthenticatedInsuranceRouteRoute
    }
    '/_authenticated/business/$businessId': {
      id: '/_authenticated/business/$businessId'
      path: '/business/$businessId'
      fullPath: '/business/$businessId'
      preLoaderRoute: typeof AuthenticatedBusinessBusinessIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedInsuranceRouteRouteChildren {
  AuthenticatedInsuranceAgentsRoute: typeof AuthenticatedInsuranceAgentsRoute
  AuthenticatedInsuranceDailyOpsRoute: typeof AuthenticatedInsuranceDailyOpsRoute
  AuthenticatedInsurancePayablesRoute: typeof AuthenticatedInsurancePayablesRoute
  AuthenticatedInsurancePayrollRoute: typeof AuthenticatedInsurancePayrollRoute
  AuthenticatedInsuranceQaRoute: typeof AuthenticatedInsuranceQaRoute
  AuthenticatedInsuranceSalesRoute: typeof AuthenticatedInsuranceSalesRoute
  AuthenticatedInsuranceTiersRoute: typeof AuthenticatedInsuranceTiersRoute
  AuthenticatedInsuranceIndexRoute: typeof AuthenticatedInsuranceIndexRoute
}

const AuthenticatedInsuranceRouteRouteChildren: AuthenticatedInsuranceRouteRouteChildren =
  {
    AuthenticatedInsuranceAgentsRoute: AuthenticatedInsuranceAgentsRoute,
    AuthenticatedInsuranceDailyOpsRoute: AuthenticatedInsuranceDailyOpsRoute,
    AuthenticatedInsurancePayablesRoute: AuthenticatedInsurancePayablesRoute,
    AuthenticatedInsurancePayrollRoute: AuthenticatedInsurancePayrollRoute,
    AuthenticatedInsuranceQaRoute: AuthenticatedInsuranceQaRoute,
    AuthenticatedInsuranceSalesRoute: AuthenticatedInsuranceSalesRoute,
    AuthenticatedInsuranceTiersRoute: AuthenticatedInsuranceTiersRoute,
    AuthenticatedInsuranceIndexRoute: AuthenticatedInsuranceIndexRoute,
  }

const AuthenticatedInsuranceRouteRouteWithChildren =
  AuthenticatedInsuranceRouteRoute._addFileChildren(
    AuthenticatedInsuranceRouteRouteChildren,
  )

interface AuthenticatedPublishersRouteChildren {
  AuthenticatedPublishersPublisherIdRoute: typeof AuthenticatedPublishersPublisherIdRoute
}

const AuthenticatedPublishersRouteChildren: AuthenticatedPublishersRouteChildren =
  {
    AuthenticatedPublishersPublisherIdRoute:
      AuthenticatedPublishersPublisherIdRoute,
  }

const AuthenticatedPublishersRouteWithChildren =
  AuthenticatedPublishersRoute._addFileChildren(
    AuthenticatedPublishersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedInsuranceRouteRoute: typeof AuthenticatedInsuranceRouteRouteWithChildren
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedBuyersRoute: typeof AuthenticatedBuyersRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInsuranceReportRoute: typeof AuthenticatedInsuranceReportRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedPublishersRoute: typeof AuthenticatedPublishersRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedBusinessBusinessIdRoute: typeof AuthenticatedBusinessBusinessIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedInsuranceRouteRoute:
    AuthenticatedInsuranceRouteRouteWithChildren,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedBuyersRoute: AuthenticatedBuyersRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInsuranceReportRoute: AuthenticatedInsuranceReportRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedPublishersRoute: AuthenticatedPublishersRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedBusinessBusinessIdRoute: AuthenticatedBusinessBusinessIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
